version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "15432:5432"
    volumes:      
      - volume-db:/var/lib/postgres
    networks:
      - postgres-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "marcosricardoss@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

volumes:    
    volume-db:     

networks: 
  postgres-network:
    driver: bridge

    